server:
  port: 8080

spring:
  datasource:
    username: root
    password: Denis16121984!
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

    show-sql: true


indexing-settings:
  sites:
    - url: http://localhost:8081/people
      name: LocalHost
    - url: http://smotret.tv
      name: Smotret.Ru
#    - url: https://vdopel.ru
#      name: Все для Opel
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

parser-settings:
  user-agent: Chrome/176.59.9.133
  referrer: www.google.com
